return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    opts = {
      transparent_background = false,
      auto_integrations = true,
      integrations = {
        blink_cmp = true,
        dap = true,
        dashboard = true,
        gitsigns = true,
        leap = true,
        lsp_trouble = true,
        markdown = true,
        mason = true,
        mini = true,
        neotest = true,
        noice = true,
        notify = true,
        quickfix = true,
        render_markdown = true,
        semantic_tokens = true,
        snacks = {
          enabled = true,
        },
        symbol_outline = true,
        treesitter = true,
        treesitter_context = true,
        ts_rainbow2 = true,
        which_key = true,
        native_lsp = {
          enabled = true,
          virtual_text = {
            errors = { "italic" },
            hints = { "italic" },
            warnings = { "italic" },
            information = { "italic" },
          },
          underlines = {
            errors = { "undercurl" },
            hints = { "italic" },
            warnings = { "undercurl" },
            information = { "italic" },
          },
        },
      },
    },
    config = function() require("catppuccin").setup {} end,
  },
}
